/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sda;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author DELL
 */
public class Search_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Search_Screen
     */
    public Search_Screen() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton_timetable = new javax.swing.JButton();
        jButton_map = new javax.swing.JButton();
        jButton_directions = new javax.swing.JButton();
        jButton_faculty = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_exit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_timetable.setBackground(new java.awt.Color(255, 255, 255));
        jButton_timetable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_timetable.setForeground(new java.awt.Color(0, 0, 204));
        jButton_timetable.setText("Time Table");
        jButton_timetable.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton_timetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_timetableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_timetableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_timetableMouseExited(evt);
            }
        });
        jButton_timetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timetableActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_timetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 190, 50));

        jButton_map.setBackground(new java.awt.Color(255, 255, 255));
        jButton_map.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_map.setForeground(new java.awt.Color(102, 102, 255));
        jButton_map.setText("Map");
        jButton_map.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton_map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_mapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_mapMouseExited(evt);
            }
        });
        jButton_map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mapActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_map, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 190, 50));

        jButton_directions.setBackground(new java.awt.Color(255, 255, 255));
        jButton_directions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_directions.setForeground(new java.awt.Color(0, 0, 204));
        jButton_directions.setText("Directions");
        jButton_directions.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton_directions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_directionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_directionsMouseExited(evt);
            }
        });
        jButton_directions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_directionsActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_directions, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 190, 60));

        jButton_faculty.setBackground(new java.awt.Color(255, 255, 255));
        jButton_faculty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_faculty.setForeground(new java.awt.Color(0, 0, 204));
        jButton_faculty.setText("Faculty Offices");
        jButton_faculty.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jButton_faculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_facultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_facultyMouseExited(evt);
            }
        });
        jButton_faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_facultyActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_faculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 190, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, 60));

        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_minimize.setText("-");
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 30, -1));

        jLabel_exit.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_exit.setText("X");
        jLabel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_exitMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sda/DisplayPage.PNG"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_timetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_timetableMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_timetableMouseClicked

    private void jButton_timetableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_timetableMouseEntered
        // TODO add your handling code here:
        jButton_timetable.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_jButton_timetableMouseEntered

    private void jButton_timetableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_timetableMouseExited
        // TODO add your handling code here:
        jButton_timetable.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton_timetableMouseExited

    private void jButton_directionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_directionsMouseEntered
        // TODO add your handling code here:
        jButton_directions.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_jButton_directionsMouseEntered

    private void jButton_directionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_directionsMouseExited
        // TODO add your handling code here:
        jButton_directions.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton_directionsMouseExited

    private void jButton_mapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mapMouseEntered
        // TODO add your handling code here:
        jButton_map.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_jButton_mapMouseEntered

    private void jButton_mapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mapMouseExited
        // TODO add your handling code here:
        jButton_map.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton_mapMouseExited

    private void jButton_facultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_facultyMouseEntered
        // TODO add your handling code here:
        jButton_faculty.setBackground(new Color(255, 153, 0));
    }//GEN-LAST:event_jButton_facultyMouseEntered

    private void jButton_facultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_facultyMouseExited
        // TODO add your handling code here:
        jButton_faculty.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton_facultyMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel_exitMouseClicked

    private void jButton_timetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timetableActionPerformed
        // TODO add your handling code here:
        TimeTable form = new TimeTable();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jButton_timetableActionPerformed

    private void jButton_mapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mapActionPerformed
        // TODO add your handling code here:
        Map form = new Map();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jButton_mapActionPerformed

    private void jButton_directionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_directionsActionPerformed
        // TODO add your handling code here:
        Search_Location form = new Search_Location();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_jButton_directionsActionPerformed

    private void jButton_facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_facultyActionPerformed
        // TODO add your handling code here:
        faculty_screen form = new faculty_screen();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_facultyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Search_Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_directions;
    private javax.swing.JButton jButton_faculty;
    private javax.swing.JButton jButton_map;
    private javax.swing.JButton jButton_timetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_exit;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
